// Meilisearch write client for the api Worker. The Worker only *indexes* into
// Meilisearch (auto-index on OCR + bulk reindex); clients query Meilisearch
// directly with a read-only key, so there is no search() here. Embeddings are
// generated by Meili itself via the Workers AI REST embedder configured in
// infra/meili/setup-index.mjs.

const INDEX = "books";

// One indexed document = one transcribed page. NOTE: bge-m3 embeds up to ~512
// tokens; very long pages get truncated for the vector half (lexical is
// unaffected). Splitting long pages into sub-chunks is a future refinement.
export interface SearchDoc {
  id: string; // file_id (Meili primary key)
  book_id: string;
  book_title: string;
  page_number: number | null;
  role: string | null;
  text: string;
}

interface MeiliEnv {
  MEILI_URL: string;
  MEILI_KEY: string;
}

async function meili({
  env,
  method,
  path,
  body,
}: {
  env: MeiliEnv;
  method: string;
  path: string;
  body?: unknown;
}): Promise<unknown> {
  const res = await fetch(`${env.MEILI_URL.replace(/\/$/, "")}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${env.MEILI_KEY}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      `Meili ${method} ${path} -> ${res.status}: ${JSON.stringify(json)}`,
    );
  }
  return json;
}

// Upsert a batch of page documents. Returns Meili's async taskUid.
export async function upsertDocs({
  env,
  docs,
}: {
  env: MeiliEnv;
  docs: SearchDoc[];
}): Promise<number> {
  const task = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/documents`,
    body: docs,
  })) as { taskUid: number };
  return task.taskUid;
}

// Delete every page document belonging to a book. Uses Meili's delete-by-filter
// (book_id is a filterable attribute); one call regardless of page count.
// Returns Meili's async taskUid.
export async function deleteDocsByBook({
  env,
  bookId,
}: {
  env: MeiliEnv;
  bookId: string;
}): Promise<number> {
  const task = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/documents/delete`,
    body: { filter: `book_id = "${bookId}"` },
  })) as { taskUid: number };
  return task.taskUid;
}
