// Thin Meilisearch client for the api Worker. The Worker pushes documents to,
// and proxies hybrid queries against, the Meilisearch instance (hosted on Fly;
// see infra/meili). Embeddings are generated by Meili itself via the Workers AI
// REST embedder configured in infra/meili/setup-index.mjs.

const INDEX = "books";
const EMBEDDER = "cfbge";

// One indexed document = one transcribed page. NOTE: bge-m3 embeds up to ~512
// tokens; very long pages get truncated for the vector half (lexical is
// unaffected). Splitting long pages into sub-chunks is a future refinement.
export interface SearchDoc {
  id: string; // file_id (Meili primary key)
  book_id: string;
  book_title: string;
  page_number: number | null;
  role: string | null;
  text: string;
}

export interface SearchHit {
  id: string;
  book_id: string;
  book_title: string;
  page_number: number | null;
  text: string;
}

interface MeiliEnv {
  MEILI_URL: string;
  MEILI_KEY: string;
}

async function meili({
  env,
  method,
  path,
  body,
}: {
  env: MeiliEnv;
  method: string;
  path: string;
  body?: unknown;
}): Promise<unknown> {
  const res = await fetch(`${env.MEILI_URL.replace(/\/$/, "")}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${env.MEILI_KEY}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      `Meili ${method} ${path} -> ${res.status}: ${JSON.stringify(json)}`,
    );
  }
  return json;
}

// Upsert a batch of page documents. Returns Meili's async taskUid.
export async function upsertDocs({
  env,
  docs,
}: {
  env: MeiliEnv;
  docs: SearchDoc[];
}): Promise<number> {
  const task = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/documents`,
    body: docs,
  })) as { taskUid: number };
  return task.taskUid;
}

// Hybrid search. semanticRatio: 0 = pure keyword (charabia), 1 = pure vector.
export async function search({
  env,
  query,
  bookId,
  semanticRatio = 0.5,
  limit = 20,
}: {
  env: MeiliEnv;
  query: string;
  bookId?: string;
  semanticRatio?: number;
  limit?: number;
}): Promise<SearchHit[]> {
  const result = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/search`,
    body: {
      q: query,
      limit,
      filter: bookId ? `book_id = "${bookId}"` : undefined,
      hybrid: { embedder: EMBEDDER, semanticRatio },
      attributesToRetrieve: [
        "id",
        "book_id",
        "book_title",
        "page_number",
        "text",
      ],
    },
  })) as { hits: SearchHit[] };
  return result.hits;
}
