// Meilisearch write client for the api Worker. The Worker only *indexes* into
// Meilisearch (auto-index on OCR + bulk reindex); clients query Meilisearch
// directly with a read-only key, so there is no search() here. Embeddings are
// generated by Meili itself via the Workers AI REST embedder configured in
// infra/meili/setup-index.mjs.

import { chunkPage } from "./chunk";

const INDEX = "books";

// One indexed document = one *chunk* of a transcribed page. A page is split into
// overlapping chunks (see chunk.ts) so each fits the bge-m3 embedder's ~512-token
// window — long pages no longer lose their tail to truncation. Chunks collapse
// back to one hit per page at query time via distinctAttribute: "file_id".
export interface SearchDoc {
  id: string; // `${file_id}#${chunkIndex}` — Meili primary key (unique per chunk)
  file_id: string; // page id: distinct key, reader nav, re-OCR cleanup
  book_id: string;
  book_title: string;
  page_number: number | null;
  role: string | null;
  text: string; // this chunk's text — searchable + embedded
  page_text: string; // full page markdown — preview display only (not searchable)
}

interface PageInput {
  file_id: string;
  book_id: string;
  book_title: string;
  page_number: number | null;
  role: string | null;
  text: string;
}

// Turn one transcribed page into its chunk documents. Returns [] for empty text.
export function buildPageDocs(page: PageInput): SearchDoc[] {
  return chunkPage(page.text).map((chunk, i) => ({
    id: `${page.file_id}#${i}`,
    file_id: page.file_id,
    book_id: page.book_id,
    book_title: page.book_title,
    page_number: page.page_number,
    role: page.role,
    text: chunk,
    page_text: page.text,
  }));
}

interface MeiliEnv {
  MEILI_URL: string;
  MEILI_KEY: string;
}

async function meili({
  env,
  method,
  path,
  body,
}: {
  env: MeiliEnv;
  method: string;
  path: string;
  body?: unknown;
}): Promise<unknown> {
  const res = await fetch(`${env.MEILI_URL.replace(/\/$/, "")}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${env.MEILI_KEY}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      `Meili ${method} ${path} -> ${res.status}: ${JSON.stringify(json)}`,
    );
  }
  return json;
}

// Upsert a batch of chunk documents. Returns Meili's async taskUid.
export async function upsertDocs({
  env,
  docs,
}: {
  env: MeiliEnv;
  docs: SearchDoc[];
}): Promise<number> {
  const task = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/documents`,
    body: docs,
  })) as { taskUid: number };
  return task.taskUid;
}

// Delete every chunk of one page. Called before re-indexing a page — chunk count
// can change between OCR runs, so stale `file_id#N` docs must be cleared first.
// Tasks are FIFO, so enqueueing this before upsertDocs guarantees ordering.
export async function deleteDocsByFile({
  env,
  fileId,
}: {
  env: MeiliEnv;
  fileId: string;
}): Promise<number> {
  const task = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/documents/delete`,
    body: { filter: `file_id = "${fileId}"` },
  })) as { taskUid: number };
  return task.taskUid;
}

// Delete every chunk document belonging to a book. Uses Meili's delete-by-filter
// (book_id is a filterable attribute); one call regardless of page count.
// Returns Meili's async taskUid.
export async function deleteDocsByBook({
  env,
  bookId,
}: {
  env: MeiliEnv;
  bookId: string;
}): Promise<number> {
  const task = (await meili({
    env,
    method: "POST",
    path: `/indexes/${INDEX}/documents/delete`,
    body: { filter: `book_id = "${bookId}"` },
  })) as { taskUid: number };
  return task.taskUid;
}

// Drop all documents in the index. Used before a full reindex so the chunk id
// scheme doesn't leave old page-level docs orphaned. Returns Meili's async taskUid.
export async function clearAllDocs({
  env,
}: {
  env: MeiliEnv;
}): Promise<number> {
  const task = (await meili({
    env,
    method: "DELETE",
    path: `/indexes/${INDEX}/documents`,
  })) as { taskUid: number };
  return task.taskUid;
}
